  shiny:
    container_name: shiny
    image: mk-mohan/shiny-finance
    restart: unless-stopped
    ports:
      - 3838:3838
    volumes:
      - ./srv/shinyapps/:/srv/shiny-server/
      - ./srv/shinylog/:/var/log/shiny-server/
