  shinyserver:
    container_name: shinyserver
    image: rocker/shiny:latest
    restart: unless-stopped
    ports:
      - 3838:3838
    volumes:
      - ./srv/shinyapps/:/srv/shiny-server/
      - ./srv/shinylog/:/var/log/shiny-server/
